name: Git Checkout
description: 'Checkout action supporting both github and non github repositories.'


inputs:
  repository:
    description: 'Repository name with owner (formatted owner/name) or git URL'
    required: true
  ref:
    description: 'The branch, tag or SHA to checkout'
    default: ''
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: '.'
  submodules: 
    description: 'Whether to checkout submodules. true|false|recuresive according to actions/checkout@v4'
    default: 'false'
  github-server-url: 
    description: 'The base URL for the GitHub instance that you are trying to clone from'
    default: 'https://github.com'

runs:
  using: "composite" 
  steps:
    - name: Checkout
      shell: bash
      run: |
        
        if [[ "${{ inputs.repository }}" =~ https?:// ]]
        then
          git_url="${{ inputs.repository }}"
        else
          git_url="${{ inputs.github-server-url }}/${{ inputs.repository }}"
        fi

        repo_path="$GITHUB_WORKSPACE/${{ inputs.path }}"

        git clone $git_url "$repo_path"
        cd "$repo_path"

        git checkout ${{ inputs.ref }}
        
        if ${{ inputs.submodules == 'true' || inputs.submodules == 'recuresive' }}
        then
          git submodule update ${{ inputs.submodules == 'recuresive' && '--recursive' || '' }}
        fi
        git checkout ${{ inputs.ref }}


