name: _Test OCI Factory
on:
  push:
    paths:
      - ".github/workflows/*"
      - "!.github/workflows/CLA-Check.yaml"
      - "!.github/workflows/PR-Validator.yaml"
      - "oci/mock-*"
      - "examples/**"
      - "src/**"
      - "!src/workflow-engine/**"

jobs:
  test-workflows:
    name: Trigger image workflows for ${{ matrix.oci-image }}
    strategy:
      matrix:
        oci-image: [mock-rock]
    uses: ./.github/workflows/Image.yaml
    with:
      oci-image-name: "${{ matrix.oci-image }}"
      upload: true
    secrets: inherit
