name: _Test OCI Factory | mock-rock
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/*"
      - ".github/actions/**"
      - "!.github/workflows/CLA-Check.yaml"
      - "!.github/workflows/PR-Validator.yaml"
      - "!.github/workflows/_Auto-updates.yaml"
      - "!.github/workflows/Continuous-Testing.yaml"
      - "!.github/workflows/CLI-Client.yaml"
      - "examples/**"
      - "oci/mock*"
      - "src/**"
      - "!tools/workflow-engine/**"
      - "!tools/cli-client/**"

jobs:
  access-check:
    name: Validate access to mock-rock
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/validate-actor
        with:
          admin-only: true
          image-path: "oci/mock-rock"
          github-token: ${{ secrets.ROCKSBOT_TOKEN }}

  test-workflows:
    name: Trigger internal tests for mock-rock
    needs: [access-check]
    uses: ./.github/workflows/Image.yaml
    with:
      oci-image-name: "mock-rock"
      upload: true
    secrets: inherit
