name: _Test OCI Factory | mock-rock
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/*"
      - "!.github/workflows/CLA-Check.yaml"
      - "!.github/workflows/PR-Validator.yaml"
      - "!.github/workflows/_Auto-updates.yaml"
      - "!.github/workflows/Continuous-Testing.yaml"
      - "examples/**"
      - "src/**"
      - "!src/workflow-engine/**"

jobs:
  test-workflows:
    name: Trigger internal tests for mock-rock
    uses: ./.github/workflows/Image.yaml
    with:
      oci-image-name: "mock-rock"
      upload: true
    secrets: inherit
