name: Continuous image testing

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  list-released-images:
    runs-on: ubuntu-latest
    name: List the revisions of released images
    outputs:
      released-revisions-matrix: ${{ steps.prepare-test-matrix.outputs.released-revisions-matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r src/tests/requirements.txt

      - name: Prepare test matrix
        id: prepare-test-matrix
        run: ./src/tests/get_released_revisions.py --oci-images-path $PWD/oci

  run-tests:
    name: Run tests for released images
    needs: [list-released-images]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list-released-images.outputs.released-revisions-matrix) }}
    uses: canonical/oci-factory/.github/workflows/Tests.yaml@main
    with:
      oci-image-name: "${{ matrix.source-image }}"
      oci-image-path: "oci/${{ matrix.name }}"
      # For continuous testing, treat every image as a standard image (non ROCK)
      is-a-rock: false
      test-from: "registry"
