name: Documentation
run-name: 'Documentation - ${{ inputs.oci-image-name }} - ${{ github.ref }}'

on:
  push:
    branches:
      - main
    paths:
      - "oci/*/documentation.y*ml"
  workflow_dispatch:
    inputs:
      oci-image-name:
        description: 'OCI image to generate the documentation for'
        required: true
      external_ref_id: #(1)
        description: 'Optional ID for unique run detection'
        required: false
        type: string
        default: "default-id"

jobs:
  validate-documentation-request:
    runs-on: ubuntu-22.04
    name: Validate documentation request
    outputs:
      oci-img-path: ${{ steps.validate-image.outputs.img-path }}
      oci-img-name: ${{ steps.validate-image.outputs.img-name }}
    steps:
      - name: ${{ inputs.external_ref_id }} #(2)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo 'Started by ${{ inputs.external_ref_id }}' >> "$GITHUB_STEP_SUMMARY"

      - uses: actions/checkout@v3

      - name: Infer images to document
        uses: tj-actions/changed-files@v35
        id: changed-files
        if: github.event_name != 'workflow_dispatch'
        with:
          dir_names: "true"
          separator: ","
          files: |
            oci/*/documentation.y*ml

      - name: Validate image from dispatch
        id: validate-image
        run: |
          set -ex

          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]
          then
            img_path="${{ steps.changed-files.outputs.all_changed_files }}"
            occurrences="${img_path//[^,]}"
            if [ ${#occurrences} -ne 0 ]
            then
              echo "ERR: can only build documentation for 1 image at a time, but trying to document ${img_path}"
              exit 1
            fi
          else
            img_path="oci/${{ inputs.oci-image-name }}"
          fi
          test -d "${img_path}"

          echo "img-name=$(basename ${img_path})" >> "$GITHUB_OUTPUT"
          echo "img-path=${img_path}" >> "$GITHUB_OUTPUT"


  do-documentation:
    runs-on: ubuntu-22.04
    name: Documentation
    needs: [validate-documentation-request]
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Setup environment
        run: pip install -r ./src/image/requirements.txt -r ./src/docs/requirements.txt

      - name: Get all revisions per track
        id: get-all-canonical-tags
        env:
          OS_USERNAME: ${{ secrets.SWIFT_OS_USERNAME }}
          OS_TENANT_NAME: ${{ secrets.SWIFT_OS_TENANT_NAME }}
          OS_PASSWORD: ${{ secrets.SWIFT_OS_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.SWIFT_OS_REGION_NAME }}
          OS_STORAGE_URL: ${{ secrets.SWIFT_OS_STORAGE_URL }}
          IMAGE_NAME: "${{ needs.validate-documentation-request.outputs.oci-img-name }}"
          SWIFT_CONTAINER_NAME: ${{ vars.SWIFT_CONTAINER_NAME }}
        run: |
          ./src/image/get_canonical_tags_from_swift.sh

      - name: Generate documentation for ${{ needs.validate-documentation-request.outputs.oci-img-name }}
        run: |
          set -ex
          python3 -m src.docs.generate_oci_doc_yaml \
            --all-revision-tags "${{ steps.get-all-canonical-tags.outputs.canonical-tags-file }}" \
            --oci-image-name "${{ needs.validate-documentation-request.outputs.oci-img-name }}" \
            --oci-image-path "${{ needs.validate-documentation-request.outputs.oci-img-path }}" \
            --repository-basename "${{ vars.repository_basename }}"
          cat ./oci/"${{ matrix.name }}"/_documentation.yaml